# Generated by Django 3.2.20 on 2023-07-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('name', models.TextField(verbose_name='NAME')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/&d/')),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
