# Generated by Django 3.2.20 on 2023-07-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avlmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Category')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['price', 'name'], 'verbose_name': 'Clothes', 'verbose_name_plural': 'Clothes'},
        ),
        migrations.AddField(
            model_name='items',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_category', to='avlmain.category'),
        ),
    ]
