# Generated by Django 3.2.20 on 2023-07-09 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avlmain', '0002_auto_20230709_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('name', models.TextField(verbose_name='NAME')),
                ('adress', models.CharField(max_length=255)),
                ('orders', models.CharField(max_length=255)),
                ('order_details', models.ImageField(upload_to='photos/%Y/%m/&d/')),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_gender', to='avlmain.category')),
            ],
            options={
                'verbose_name': 'Clothes',
                'verbose_name_plural': 'Clothes',
                'ordering': ['time', 'name'],
            },
        ),
    ]
